### ISSUE TITLE
logLevel issue

### ISSUE THREAD

**Issue by Supermarco333** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#102]
Hello,
I updated my HB setup with the last version of your plugin (1.9.4). I'm currently facing this issue:

```
[7/6/2021, 12:11:51 PM] TypeError: Cannot read property 'logLevel' of undefined
    at new HomebridgeMagichomeDynamicPlatform (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:59:37)
    at /usr/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:29)
```

Thanks.

**Comment by Zacknetic** [comment]
Hi there. 
- Please login to your homebridge UI
- cl￼ick plugins
- under "Homebridge magichome Dynamic Platform">click settings
- scroll all the way to the bottom of the list > wave hello at the new logging option that is causing your issue> click save
- restart Homebridge. 

Let me know how that goes.

**Comment by jimmyobomsawin** [comment]
Had the same problem and saving the settings again fixed it. Thanks @Zacknetic !

**Comment by Zacknetic** [comment]
> Had the same problem and saving the settings again fixed it. Thanks @Zacknetic !

Awesome! Happy to help.

**Comment by Supermarco333** [comment]
Everything up and running ! Thanks for that.
