### ISSUE TITLE
[BUG] Not found led strip ws2812b

### ISSUE THREAD

**Issue by faganello60** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#142]
LOG
[homebridge-magichome-dynamic-platform] 
Discovered 1 devices.

[30/09/2023, 18:44:10] [homebridge-magichome-dynamic-platform] [discovered+cached] platform.ts discoverDevices() accessory creation has thrown the following error: TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Hash.update (node:internal/crypto/hash:109:11)
    at Object.generate (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:138:49)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [stack]: 'TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined\n' +
    '    at new NodeError (node:internal/errors:399:5)\n' +
    '    at Hash.update (node:internal/crypto/hash:109:11)\n' +
    '    at Object.generate (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)\n' +
    '    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:138:49)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
  [message]: 'The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined',
  [toString]: [Function: value] { [length]: 0, [name]: 'value' },
  code: 'ERR_INVALID_ARG_TYPE',
  [Symbol(kIsNodeError)]: true
}

**Comment by nzzane** [comment]
Any updates to this? Having the same issue
