### ISSUE TITLE
No longer working after most recent update

### ISSUE THREAD

**Issue by dougops** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#20]
Hi, I previously had a MagicHome RGB LED strip set up with Homebridge which was working fine in both Homebridge and the Homekit app.

I've added another controller/strip for another part of the house, it seemed to register fine and was working but was spotty. I noticed both Homebridge and the Magichome plugin platform had updates so i ran them and since then the plugin does not work anymore. I've tried resintalling both from fresh and the error is the same.

The error being thrown up at the start is:
[8/24/2020, 20:12:51] [homebridge-magichome-dynamic-platform] TypeError: accessoryType[existingAccessory.context.controller] is not a constructor
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (C:\Users\#####\AppData\Roaming\npm\node_modules\homebridge-magichome-dynamic-platform\src\platform.ts:300:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Any ideas?

**Comment by dougops** [comment]
Ok, can disregard this post.

I had the homebridge forget all cached accessories in the actual Homebridge settings, gave it a couple of restarts and it found them both and seem to be working fine now.
