### ISSUE TITLE
Latest version crashing Homebridge

### ISSUE THREAD

**Issue by ginnjuicewv** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#24]
Hey there, the latest version of the plugin is causing Homebridge to crash for me; here's the output from the console.

`[9/3/2020, 09:01:36] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at DimmerStrip.getBrightness (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/PlatformAccessory.ts:233:5)
    at Brightness.emit (events.js:327:22)
    at Brightness.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Brightness.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1145:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
[9/3/2020, 09:01:36] Got SIGTERM, shutting down Homebridge...`

Thanks

**Comment by Zacknetic** [comment]
Hey, thank you for your patience.

This seems odd. Perhaps a device got added twice somehow as that function shouldn't call more than once.

Regardless, I've updated the code to be a bit more clean to help with version type issues. Please update in config ui x > plugins > homebridge-magichome-dynamic-platform > update. (!Important!) Next purge all magic-home accessories by going to config ui x > plugins > homebridge-magichome-dynamic-platform > settings > checkmark "Prune All Accessories Next Restart (Warning Dangerous!)" > restart homebridge at least twice > un-checkmark  "Prune All Accessories Next Restart (Warning Dangerous!)" > restart homebridge.

See if that works for you. Otherwise please upload your homebridge.log

Thank you

**Comment by Zacknetic** [comment]
@ginnjuicewv 

I have posted another update which you may find solves your issue. I am closing this due to inactivity, but feel free to re-open it if you need additional help.

Please update your plugin to version 1.5.1 . Note: if you are updating from version 1.4.x you'll need to purge all your magichome devices after updating. Then restart homebridge to rescan.

With help, I found a bug in the code that caused duplicate device to register if the user had multiple subnets. Thus the crash. I was trying to scan on more than one subnet but didn't account for devices showing up on more than one.
