### ISSUE TITLE
New LED Strip Controller causes Homebridge crash

### ISSUE THREAD

**Issue by muzzymate** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#35]
I recently purchased this MagicHome LED strip controller and LED strip set: https://www.amazon.com/gp/product/B07VPP4SMH/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

When Homebridge is starting up the following error messages are logged to the console and the Homebridge instance crashes. Placing the device in the blacklist allows the Homebringe instance to run as normally, but of course, then I am not able to control this device in Homekit. Any thoughts or other pieces of information that you might need to diagnose?

Thanks!

[10/26/2020, 12:01:26 AM] [homebridge-magichome-dynamic-platform] 
Registering new accessory 'Simple GRB' 
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E4761CA8C' 
IP-Address: '10.0.0.228' 
Light Version 8 
Version Modifier: 51
Protocol Version: 1

[10/26/2020, 12:01:26 AM] [homebridge-magichome-dynamic-platform] 
Registered 3 Magichome device(s). 
New devices: 2 
Cached devices that were seen this restart: 1 
Cached devices that were not seen this restart: 0

[10/26/2020, 12:01:26 AM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[10/26/2020, 12:01:26 am] [SmartThings] ERROR: uncaughtException: read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[10/26/2020, 12:01:26 AM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[10/26/2020, 12:01:26 am] [SmartThings] ERROR: uncaughtException: read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

**Comment by m0v1em4n** [comment]
Just installed this today and it crashed Homebridge with the following error

[10/27/2020,` 2:02:29 PM] [homebridge-magichome-dynamic-platform] 
Registered 4 Magichome device(s). 
New devices: 2 
Cached devices that were seen this restart: 2 
Cached devices that were not seen this restart: 0

[10/27/2020, 2:02:29 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:208:20)
uncaughtException: read ECONNRESET
uncaughtException: read ECONNRESET
[10/27/2020, 2:02:29 PM] Got SIGTERM, shutting down Homebridge...
[10/27/2020, 2:02:29 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:208:20)
uncaughtException: read ECONNRESET
uncaughtException: read ECONNRESET
[10/27/2020, 2:02:29 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:208:20)
uncaughtException: read ECONNRESET
uncaughtException: read ECONNRESET
[10/27/2020, 2:02:29 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:208:20)
uncaughtException: read ECONNRESET
uncaughtException: read ECONNRESET

**Comment by Zacknetic** [comment]
Hello, 
 @m0v1em4n @muzzymate Thank you for bringing this to my attention.
This seems to have been introduced by the latest update. I will investigate and post back here.

**Comment by Zacknetic** [comment]
@m0v1em4n @muzzymate 
Please update your plugin to version 1.5.1 . Note: if you are updating from version 1.4.x you'll need to purge all your magichome devices first.

With help, I found a bug in the code that caused duplicate device to register if the user had multiple subnets. Thus the crash. I was trying to scan on more than one subnet but didn't account for devices showing up on more than one.

Let me know how it goes. Thank you.

**Comment by Zacknetic** [comment]
Closing this issue for now. Please reopen if the problem persists. Thank you.
