### ISSUE TITLE
1.51 no control

### ISSUE THREAD

**Issue by CVHvisuals** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#38]
Registering new accessory 'Simple GRB' 
Model: 'HF-LPB100-ZJ200' 
Unique ID: 'XXXXXXXXXXX' 
IP-Address: '10.0.1.17' 
Light Version 1 
Version Modifier: 37
Protocol Version: 1

Can only turn on and off. Unable to change color selection. I have 4 units with the same result.
1.45 I am able to change the color, although the greens and reds are mismatched.
Any suggestions, thanks!
Chris

**Comment by CVHvisuals** [comment]
Here is a link to the controllers. They are currently configured 
to RGBWW

https://www.amazon.com/gp/product/B01AA6221S/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by Zacknetic** [comment]
I've added new logic in the latest update which may work... if not. Please upload a complete homebridge log with debugging turned on.

Update the plugin > enable 'prune all accessories next restart' > restart > disable 'prune all accessories next restart' > restart. See if that solves the problem.

Thank you.

**Comment by CVHvisuals** [comment]
Ive update the version and applied the pruning steps. Results are no devices added. Here is the log:

[11/10/2020, 7:58:26 AM] [homebridge-magichome-dynamic-platform] 
Discovered 4 devices.
[11/10/2020, 7:58:26 AM] [homebridge-magichome-dynamic-platform] 
Assigning controller to device: UniqueId: 'ACCF2397FE7E' 
IpAddress '10.0.1.15' 
Model: 'HF-LPB100-ZJ200'
Firmware Version: 1 
Device Type: '25'

[11/10/2020, 7:58:26 AM] [homebridge-magichome-dynamic-platform] Unknown device type: '25'... type probably cannot be set. Trying anyway with default GRB device
[11/10/2020, 7:58:26 AM] [homebridge-magichome-dynamic-platform] Please create an issue at https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/issues and post your homebridge.log
[11/10/2020, 7:58:26 AM] [homebridge-magichome-dynamic-platform] TypeError: Cannot read property 'controllerType' of undefined
    at HomebridgeMagichomeDynamicPlatform.determineController (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:484:72)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:240:33)
[11/10/2020, 7:58:26 AM] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0

**Comment by Zacknetic** [comment]
Okay, there was not logic for 0x25 rgbww device type.  Just updated with that logic so update your plugin to 1.6.2.

Update the plugin > enable 'prune all accessories next restart' > restart > disable 'prune all accessories next restart' > restart. This will most likely solve your issue if the devices are correctly purged.

Also, feel free to join the official [MagicHome Discord Server](https://discord.gg/c8xpmZSNZC). I tend to be more responsive there.

Thank you.

**Comment by CVHvisuals** [comment]
That works! Thank you.

**Comment by Zacknetic** [comment]
Happy to hear. Closing this issue. Feel free to join the discord and if you get a moment, take a look at my [GitHub Sponsors](https://github.com/sponsors/Zacknetic) page. It helps me out a lot.

Thanks again.
