### ISSUE TITLE
RGB device issue

### ISSUE THREAD

**Issue by Zacknetic** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#39]
@Zacknetic I'm getting the same problem. I did the steps as above with no help.

```
11/2/2020, 10:40:20 PM [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.
11/2/2020, 10:40:21 PM [homebridge-magichome-dynamic-platform] 
 Platform.ts.createAccessory(): 
Assigning controller to device: UniqueId: 'C82E475FC37D' 
IpAddress '192.168.0.146' 
Model: 'AK001-ZJ2131'
Original Light Version: 8
Light Version Modifier: 51
11/2/2020, 10:40:21 PM [homebridge-magichome-dynamic-platform] ( Modified) Light version: 1 matches known device type records
11/2/2020, 10:40:21 PM Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
11/2/2020, 10:40:21 PM HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
11/2/2020, 10:40:21 PM [homebridge-magichome-dynamic-platform] 
Registering new accessory 'Simple GRB' 
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E475FC37D' 
IP-Address: '192.168.0.146' 
Light Version 8 
Version Modifier: 51
Protocol Version: 1
11/2/2020, 10:40:21 PM [homebridge-magichome-dynamic-platform] 
Registered 1 Magichome device(s). 
New devices: 1 
Cached devices that were seen this restart: 0 
Cached devices that were not seen this restart: 0
11/2/2020, 10:40:21 PM Got SIGTERM, shutting down Bridge...
11/2/2020, 10:40:21 PM Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
11/2/2020, 10:40:21 PM Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
```

This is the item I purchased: [Outdoor LED Strip](https://www.amazon.ca/gp/product/B0814PMDSP/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1)

_Originally posted by @jzdeb in https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/issues/37#issuecomment-720916595_

**Comment by Zacknetic** [comment]
Creating a new issue here to keep things separate.

**Comment by Zacknetic** [comment]
@jzdeb This looks like a protocol issue. I would like to try adding some logic to switch your device to the 9 byte protocol. Will post an update tomorrow.

**Comment by Zacknetic** [comment]
@jzdeb Please update > purge all magichome devices > restart. Let me know how it goes.

**Comment by jzdeb** [comment]
I downloaded a clean image of homebridge to test and installed just this plugin. Getting reboot loop now.

`[09/11/2020, 22:25:53] Homebridge is running on port 51993.
[09/11/2020, 22:25:55] [homebridge-magichome-dynamic-platform] ( Scan: 1 ) Discovered zero devices... rescanning...
[09/11/2020, 22:25:55] [homebridge-magichome-dynamic-platform] Scanning broadcast-address: '192.168.0.255' for Magichome devices... 

[09/11/2020, 22:25:57] [homebridge-magichome-dynamic-platform] ( Scan: 2 ) Discovered zero devices... rescanning...
[09/11/2020, 22:25:57] [homebridge-magichome-dynamic-platform] Scanning broadcast-address: '192.168.0.255' for Magichome devices... 

[09/11/2020, 22:25:59] [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.

[09/11/2020, 22:26:00] [homebridge-magichome-dynamic-platform] 
Assigning controller to device: UniqueId: 'C82E475FC37D' 
IpAddress '192.168.0.146' 
Model: 'AK001-ZJ2131'
Firmware Version: 8 
Device Type: '33'

[09/11/2020, 22:26:00] [homebridge-magichome-dynamic-platform] Light Version: '33' with Firmware Version: '8' matches known device type records
[09/11/2020, 22:26:00] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[09/11/2020, 22:26:00] Got SIGTERM, shutting down Homebridge...
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[09/11/2020, 22:26:00] [homebridge-magichome-dynamic-platform] Registering new accessory...!
1 - Display Name: 'Simple GRB' 
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E475FC37D' 
IP-Address: '192.168.0.146' 
Firmware Version: 8 
Device Type: '33'

[09/11/2020, 22:26:00] [homebridge-magichome-dynamic-platform] Successfully pruned accessory: Simple GRB which had not being seen for ( 0 ) restart(s).

[09/11/2020, 22:26:00] [homebridge-magichome-dynamic-platform] 
Registered 1 Magichome device(s). 
New devices: 1 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0

[09/11/2020, 22:26:00] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[09/11/2020, 22:26:00] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[09/11/2020, 22:26:05] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[09/11/2020, 22:26:10] [HB Supervisor] Restarting Homebridge...`

**Comment by Zacknetic** [comment]
Okay, well that's super odd. Simple GRB devices SHOULD use the 8 byte protocol. I've added logic which tests each device which protocol it likes. See below:

` if(this.eightByteProtocol == 0){
      this.send([0x31, r, g, b, 0x00, mask, 0x0F]); //8th byte checksum calculated later in send()
    } else if(this.eightByteProtocol == 1){
      this.send([0x31, r, g, b, 0x00, 0x00, mask, 0x0F]);
    } else if (this.eightByteProtocol == 2){
      this.eightByteProtocol = (await this.send([0x31, r, g, b, 0x00, 0x00, mask, 0x0F])) == undefined ? 0 : 1;
      this.send([0x31, r, g, b, 0x00, mask, 0x0F]); //8th byte checksum calculated later in send()
    }`

If the device responds "undefined" from the 9 byte protocol, it will switch to the other protocol. 

If this issue was happening after you tried to control the device, this might solve the problem, but if it happened before you tried to control the device... well there may be further issues. 

Let me know.

**Comment by jzdeb** [comment]
I've updated to version 1.6.2, Same reboot loop.

```
[10/11/2020, 22:38:12] Homebridge is running on port 51993.
[10/11/2020, 22:38:17] [Vivint] Device not (yet) supported [ID]:5 [Type]:energy_service [EquipmentCode]:undefined [Name]:undefined
[10/11/2020, 22:38:17] [Vivint] Device not (yet) supported [ID]:69 [Type]:lgit_poe_wifi_device [EquipmentCode]:undefined [Name]:Camera 1-Bridge
[10/11/2020, 22:38:17] [Vivint] Removing 0 accessories
[10/11/2020, 22:38:17] [Vivint] Adding 0 accessories
[10/11/2020, 22:38:17] [homebridge-magichome-dynamic-platform] ( Scan: 1 ) Discovered zero devices... rescanning...
[10/11/2020, 22:38:17] [homebridge-magichome-dynamic-platform] Scanning broadcast-address: '192.168.0.255' for Magichome devices... 

[10/11/2020, 22:38:19] [homebridge-magichome-dynamic-platform] ( Scan: 2 ) Discovered zero devices... rescanning...
[10/11/2020, 22:38:19] [homebridge-magichome-dynamic-platform] Scanning broadcast-address: '192.168.0.255' for Magichome devices... 

[10/11/2020, 22:38:21] [homebridge-magichome-dynamic-platform] ( Scan: 3 ) Discovered zero devices... rescanning...
[10/11/2020, 22:38:21] [homebridge-magichome-dynamic-platform] Scanning broadcast-address: '192.168.0.255' for Magichome devices... 

[10/11/2020, 22:38:23] [homebridge-magichome-dynamic-platform] ( Scan: 4 ) Discovered zero devices... rescanning...
[10/11/2020, 22:38:23] [homebridge-magichome-dynamic-platform] Scanning broadcast-address: '192.168.0.255' for Magichome devices... 

[10/11/2020, 22:38:25] [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.

[10/11/2020, 22:38:25] [homebridge-magichome-dynamic-platform] 
Assigning controller to device: UniqueId: 'C82E475FC37D' 
IpAddress '192.168.0.146' 
Model: 'AK001-ZJ2131'
Firmware Version: 8 
Device Type: '33'

[10/11/2020, 22:38:25] [homebridge-magichome-dynamic-platform] Light Version: '33' with Firmware Version: '8' matches known device type records
[10/11/2020, 22:38:25] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[10/11/2020, 22:38:25] [homebridge-magichome-dynamic-platform] Registering new accessory...!
1 - Display Name: 'Simple GRB' 
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E475FC37D' 
IP-Address: '192.168.0.146' 
Firmware Version: 8 
Device Type: '33'

[10/11/2020, 22:38:25] [homebridge-magichome-dynamic-platform] Successfully pruned accessory: Simple GRB which had not being seen for ( 0 ) restart(s).

[10/11/2020, 22:38:25] [homebridge-magichome-dynamic-platform] 
Registered 1 Magichome device(s). 
New devices: 1 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0

[10/11/2020, 22:38:25] Got SIGTERM, shutting down Homebridge...
[10/11/2020, 22:38:26] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[10/11/2020, 22:38:26] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[10/11/2020, 22:38:31] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null`

**Comment by Zacknetic** [comment]
Pruning is still turned on. This may not be the source of the issue, but this
`
[10/11/2020, 22:38:25] [homebridge-magichome-dynamic-platform] Successfully pruned accessory: Simple GRB which had not being seen for ( 0 ) restart(s).
`
means that you need to uncheckmark pruning in your settings.

**Comment by Zacknetic** [comment]
Hi, version 1.7.3 has brought improvements to the networking functions of this plugin. Another user with the exact issue has since had this problem solved. Please let me know if it does for you after updating. Thank you.

**Comment by jzdeb** [comment]
1.7.3 has resolved the issue.

Thanks so much for your work on this project.

**Comment by Zacknetic** [comment]
Very happy to hear it! Thanks for sticking around. Enjoy!
