### ISSUE TITLE
Devices not responding since 1.8.1

### ISSUE THREAD

**Issue by WeManuel127** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#50]
Hey there, 
since I updated to 1.8.1 I have some RGBW-controllers that don't respond in Homebridge, although I can control them in the MagicHome App.

This is the log inside HOOBS:

```
21.11.2020, 10:29:21 [homebridge-magichome-dynamic-platform] 
Discovered 3 devices.
21.11.2020, 10:29:21 [homebridge-magichome-dynamic-platform] TypeError: Cannot read property 'controllerType' of undefined
    at HomebridgeMagichomeDynamicPlatform.printDeviceInfo (/home/hoobs/.hoobs/node_modules/homebridge-magichome-dynamic-platform/dist/platform.js:301:237)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-magichome-dynamic-platform/dist/platform.js:171:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
21.11.2020, 10:29:21 [homebridge-magichome-dynamic-platform] 
Warning! Continuing to register cached accessory despite not being seen for 1 restarts.
21.11.2020, 10:29:21 [homebridge-magichome-dynamic-platform] 
Warning! Continuing to register cached accessory despite not being seen for 2 restarts.
21.11.2020, 10:29:21 [homebridge-magichome-dynamic-platform] 
Registered 2 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 2
21.11.2020, 10:29:28 (node:14733) UnhandledPromiseRejectionWarning: Error: connection timed out
21.11.2020, 10:29:28 at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/tuyapi/index.js:303:18)
21.11.2020, 10:29:28 at Object.onceWrapper (events.js:299:28)
21.11.2020, 10:29:28 at Socket.emit (events.js:210:5)
21.11.2020, 10:29:28 at Socket._onTimeout (net.js:469:8)
21.11.2020, 10:29:28 at listOnTimeout (internal/timers.js:531:17)
21.11.2020, 10:29:28 at processTimers (internal/timers.js:475:7)
21.11.2020, 10:29:28 (node:14733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
21.11.2020, 10:29:28 (node:14733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
21.11.2020, 10:29:38 (node:14733) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
21.11.2020, 10:29:38 at /home/hoobs/.hoobs/node_modules/tuyapi/index.js:622:13
21.11.2020, 10:29:38 at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/p-timeout/index.js:25:13)
21.11.2020, 10:29:38 at listOnTimeout (internal/timers.js:531:17)
21.11.2020, 10:29:38 at processTimers (internal/timers.js:475:7)
21.11.2020, 10:29:38 (node:14733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
21.11.2020, 10:29:38 (node:14733) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
21.11.2020, 10:29:38 at /home/hoobs/.hoobs/node_modules/tuyapi/index.js:622:13
21.11.2020, 10:29:38 at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/p-timeout/index.js:25:13)
21.11.2020, 10:29:38 at listOnTimeout (internal/timers.js:531:17)
21.11.2020, 10:29:38 at processTimers (internal/timers.js:475:7)
21.11.2020, 10:29:38 (node:14733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by Zacknetic** [comment]
Hi, thank you for the log. It seems the update has caused some data loss. Do you mind pruning these 3 devices in by enabling prune all in-settings > save > restart > disable prune all > restart? 

> On Nov 21, 2020, at 4:33 AM, WeManuel127

**Comment by x5nder** [comment]
Same issue here. Don't think that pruning all accessories helped (FYI, I have 2 different LED strips)...

```
[11/21/2020, 11:00:28 AM] [homebridge-magichome-dynamic-platform] 
Discovered 2 devices.

[11/21/2020, 11:00:28 AM] [homebridge-magichome-dynamic-platform] TypeError: Cannot read property 'controllerType' of undefined
    at HomebridgeMagichomeDynamicPlatform.printDeviceInfo (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:394:46)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:221:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[11/21/2020, 11:00:28 AM] [homebridge-magichome-dynamic-platform] Successfully pruned accessory: LED Strip which had not being seen for ( 0 ) restart(s).

[11/21/2020, 11:00:28 AM] [homebridge-magichome-dynamic-platform] Successfully pruned accessory: LED Strip which had not being seen for ( 2 ) restart(s).

[11/21/2020, 11:00:28 AM] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0
```

**Comment by Zacknetic** [comment]
I’m looking into the root cause but you still have pruning enabled. Disable it and restart. Let me know what happens next.

**Comment by x5nder** [comment]
Whoops, you're correct. Now both devices are recognized and no errors appear anymore! Thanks!

**Comment by edmarts** [comment]
Hi!! I'm back :(

I also upgraded to version 1.8.1 and mess up all over again.
When I turn on a device, it turns off right away and don's stay on... I have to try two or three times to turn on.
I removed the device and restarted the homebridge and now the device does not reappear any more.
Another problem I encountered is when a scene turns off a device that is already off, it blinks.

**Comment by edmarts** [comment]
Hi, I remove all devices again... prune all in-settings > save > restart > disable prune all > restart
Sounds like is normal again... I did some tests and all works again... crazy not? hahaha

**Comment by Zacknetic** [comment]
@x5nder good to hear.
@edmarts 1.8.x introduced a bug that allowed for data loss. That's probably what happened but if you encounter another problem please open a separate issue. I'd like to avoid piggybacking on issues unless they are very similar to the OP. 

@WeManuel127 Please update to v1.8.2. No pruning or deleting needed! Let me know!

**Comment by WeManuel127** [comment]
@Zacknetic Updating to 1.8.2 seems to have worked perfectly fine, they all work in HomeKit again. 
Thank you for the super quick support :)
