### ISSUE TITLE
Latest update broke plugin

### ISSUE THREAD

**Issue by x5nder** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#70]
I updated to the latest version of the plugin yesterday (1.9.1) and my light strips aren't working anymore. Homebridge log shows this error:

```
[12/11/2020, 11:19:36 AM] [homebridge-magichome-dynamic-platform] 
Discovered 2 devices.

[12/11/2020, 11:19:36 AM] [homebridge-magichome-dynamic-platform] 1 -Registering existing accessory...
 Display Name: undefined 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ200' 
Unique ID: '60019496E275' 
IP-Address: '192.168.178.164' 
Hardware Version: '51' 
Firmware Version: '4' 

[12/11/2020, 11:19:36 AM] [homebridge-magichome-dynamic-platform] platform.ts discoverDevices() accessory creation has thrown the following error: TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor
    at HomebridgeMagichomeDynamicPlatform.registerExistingAccessory (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:404:28)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:159:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  [stack]: 'TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor\n' +
    '    at HomebridgeMagichomeDynamicPlatform.registerExistingAccessory (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:404:28)\n' +
    '    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:159:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
  [message]: 'accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor'
}
[12/11/2020, 11:19:36 AM] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0
```

Have already tried Prune all - restart - disable prune all - restart, to no avail. 

Reverted to 1.8.5 but that isn't working anymore either:

```
[12/11/2020, 11:25:27 AM] [homebridge-magichome-dynamic-platform] 
Discovered 2 devices.
[12/11/2020, 11:25:27 AM] [homebridge-magichome-dynamic-platform] TypeError: Cannot read property 'toString' of undefined
    at HomebridgeMagichomeDynamicPlatform.printDeviceInfo (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:390:51)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:221:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[12/11/2020, 11:25:27 AM] [homebridge-magichome-dynamic-platform] TypeError: Cannot read property 'toString' of undefined
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:248:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[12/11/2020, 11:25:27 AM] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0
```

**Comment by x5nder** [comment]
Tried your latest 1.9.2beta6 and that seems to have fixed it!

```
[12/11/2020, 11:29:06 AM] [homebridge-magichome-dynamic-platform] 1 - Registering existing accessory...
Display Name: 'GRBW Strip' 
Controller Logic Type: 'GRBStrip'  
Model: 'AK001-ZJ200' 
Unique ID: '60019496E275' 
IP-Address: '192.168.178.164' 
Hardware Version: '33' 
Firmware Version: '4' 

HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[12/11/2020, 11:29:06 AM] [homebridge-magichome-dynamic-platform] Successfully pruned accessory: GRBW Strip which had not being seen for ( 0 ) restart(s).

[12/11/2020, 11:29:07 AM] [homebridge-magichome-dynamic-platform] 1 - Registering new accessory...!
Display Name: 'RGBW Simultaneous' 
Controller Logic Type: 'RGBWStrip'  
Model: 'AK001-ZJ200' 
Unique ID: '600194ABF77A' 
IP-Address: '192.168.178.45' 
Hardware Version: '4' 
Firmware Version: '5' 

HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
```

**Comment by isramos** [comment]
Glad to hear that 1.9.2beta6 fixed the issue.
